export const products = [
    {
        id: "FN-UX-OUTW000018",
        name: "LOOSE FIT DENIM JACKET",
        url: "",
        price: 510,
        color: "Black",
        description: "Acne Studios black denim jacket features a loose fit with elongated sleeves and hem length. Crafted from rigid denim made of organically grown cotton.",
        imageUrl: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-product-image.jpg" ,
        hoverUrl: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-hover.jpg",
        infoImageUrl: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/LOOSE-DENIM-JACKET-info-image.png",
        infoImageUrl2: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-back.jpg",
        infoImageUrl3: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-left-profile.jpg",
        infoImageUrl4: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-detail.jpg",
        infoImageUrl5: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-closeup.jpg",
        infoImageUrl6: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-product-image.jpg",
    },
    {
        id: "FN-WN-OUTW000514",
        name: "RELAXED FIT DENIM JACKET",
        url: "",
        price: 500,
        color: "Dark Grey",
        description: "Denim jacket is cut to a relaxed fit with dropped shoulders, extra long sleeves and a cropped length. Crafted from non-stretch denim in a dark grey wash.",
        imageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-product-image.jpg",
        hoverUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-hover.jpg",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "",
        infoImageUrl3: "",
        infoImageUrl4: "",
        infoImageUrl5: "",
        infoImageUrl6: "",
    },
    {
        id: "Acne Studios 2023F Faded Black",
        name: "LOOSE FIT JEANS",
        url: "",
        price: 390,
        color: "Black",
        description: "Acne Studios dark grey loose fit jeans feature a 5-pocket denim construction with a mid-waist, wide leg and long length.",
        imageUrl: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-jeans-product-image.jpg",
        hoverUrl: "url(/assets/products/denim/jackets/LOOSE FIT DENIM JACKET/C90095-900_UNISEX-WOMAN_A.png)",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-back.jpg",
        infoImageUrl3: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-left-profile.jpg",
        infoImageUrl4: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-detail.jpg",
        infoImageUrl5: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-closeup.jpg",
        infoImageUrl6: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-product-image.jpg",
    },
    {
        id: "Acne Studios 2023 Vintage Black",
        name: "RELAXED FIT JEANS",
        url: "",
        price: 380,
        color: "Black",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-denim-jeans-product-image.jpg",
        hoverUrl: "ur;(/assets/products/denim/jackets/LOOSE FIT DENIM JACKET/C90095-900_UNISEX-WOMAN_A.png)",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "",
        infoImageUrl3: "",
        infoImageUrl4: "",
        infoImageUrl5: "",
        infoImageUrl6: "",
    },
    {
        id: "FN-UX-EYEW000064",
        name: "BLACK METAL FRAME SUNGLASSES",
        url: "",
        price: 380,
        color: "Black",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/glasses/BLACK-METAL-FRAME/black-metal-frame-product-image.jpg",
        hoverUrl: "ur;(/assets/products/denim/jackets/LOOSE FIT DENIM JACKET/C90095-900_UNISEX-WOMAN_A.png)",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "",
        infoImageUrl3: "",
        infoImageUrl4: "",
        infoImageUrl5: "",
        infoImageUrl6: "",
    },
    {
        id: "FN-UX-EYEW000065",
        name: "WHITE METAL FRAME SUNGLASSES",
        url: "",
        price: 380,
        color: "White",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/glasses/WHITE-METAL-FRAME/white-metal-frame-product-imahe.jpg",
        hoverUrl: "ur;(/assets/products/denim/jackets/LOOSE FIT DENIM JACKET/C90095-900_UNISEX-WOMAN_A.png)",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "",
        infoImageUrl3: "",
        infoImageUrl4: "",
        infoImageUrl5: "",
        infoImageUrl6: "",
    },
    {
        id: "FN-UX-JEWE000430",
        name: "HEART CHARM NECKLACE",
        url: "",
        price: 380,
        color: "Silver",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/accessories/HEART-CHARM-NECKLACE/heart-charm-necklace.jpg",
        hoverUrl: "ur;(/assets/products/denim/jackets/LOOSE FIT DENIM JACKET/C90095-900_UNISEX-WOMAN_A.png)",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "",
        infoImageUrl3: "",
        infoImageUrl4: "",
        infoImageUrl5: "",
        infoImageUrl6: "",
    },
    {
        id: "FN-UX-JEWE000422",
        name: "MULTI HOOP EARRINGS",
        url: "",
        price: 380,
        color: "Black",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/accessories/MULTI-HOOP-EARRINGS/multi-hoop-earrings-product-image.jpg",
        hoverUrl: "ur;(/assets/products/denim/jackets/LOOSE FIT DENIM JACKET/C90095-900_UNISEX-WOMAN_A.png)",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "",
        infoImageUrl3: "",
        infoImageUrl4: "",
        infoImageUrl5: "",
        infoImageUrl6: "",
    },
    
    
]