export const products = [
    {
        id: "FN-UX-OUTW000018",
        name: "LOOSE FIT DENIM JACKET",
        url: "",
        price: 510,
        color: "Black",
        description: "Acne Studios black denim jacket features a loose fit with elongated sleeves and hem length. Crafted from rigid denim made of organically grown cotton.",
        imageUrl: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-product-image.jpg" ,
        hoverUrl: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-hover.jpg",
        infoImageUrl: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/LOOSE-DENIM-JACKET-info-image.png",
        infoImageUrl2: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-back.jpg",
        infoImageUrl3: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-left-profile.jpg",
        infoImageUrl4: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-detail.jpg",
        infoImageUrl5: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-jacket-closeup.jpg",
        infoImageUrl6: "/assets/products/denim/jackets/LOOSE-FIT-DENIM-JACKET/loose-fit-denim-product-image.jpg",
        count: 1
    },
    {
        id: "FN-WN-OUTW000514",
        name: "RELAXED FIT CROPPED DENIM JACKET",
        url: "",
        price: 500,
        color: "Dark Grey",
        description: "Denim jacket is cut to a relaxed fit with dropped shoulders, extra long sleeves and a cropped length. Crafted from non-stretch denim in a dark grey wash.",
        imageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-denim-fit-jacket-product.jpg",
        hoverUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-hover.jpg",
        infoImageUrl: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-fit-denim-jacket-info-image.png",
        infoImageUrl2: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-denim-fit-jacket-back.jpg",
        infoImageUrl3: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-denim-fit-jacket-left-profile.jpg",
        infoImageUrl4: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-denim-fit-jacket-detail.jpg",
        infoImageUrl5: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-denim-fit-jacket-left-closeup.jpg",
        infoImageUrl6: "/assets/products/denim/jackets/RELAXED-FIT-DENIM-JACKET/relaxed-denim-fit-jacket-product.jpg",
        count: 1
    },
    {
        id: "Acne-Studios-2023F-Faded Black",
        name: "LOOSE FIT JEANS",
        url: "",
        price: 390,
        color: "Black",
        description: "Acne Studios dark grey loose fit jeans feature a 5-pocket denim construction with a mid-waist, wide leg and long length.",
        imageUrl: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-jeans-product-image.jpg",
        hoverUrl: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-denim-hover-image.png",
        infoImageUrl: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-jeans-info-image.png",
        infoImageUrl2: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-jeans-back.jpg",
        infoImageUrl3: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-jeans-right-profile.jpg",
        infoImageUrl4: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-jeans-detail.jpg",
        infoImageUrl5: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-jeans-detail-back.jpg",
        infoImageUrl6: "/assets/products/denim/jeans/LOOSE-FIT-JEANS/loose-fit-denim-product-image.jpg",
        count: 1
    },
    {
        id: "Acne-Studios-2023-Vintage Black",
        name: "RELAXED FIT JEANS",
        url: "",
        price: 380,
        color: "Black",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-denim-jeans-product-image.jpg",
        hoverUrl: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-jeans-hover-image.png",
        infoImageUrl: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-jeans-info-image.jpg.png",
        infoImageUrl2: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-jeans-back.jpg",
        infoImageUrl3: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-jeans-left-profile.jpg",
        infoImageUrl4: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-jeans-detail.jpg",
        infoImageUrl5: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-jeans-back-detail.jpg",
        infoImageUrl6: "/assets/products/denim/jeans/RELAXED-FIT-JEANS/relaxed-fit-jeans-product-image.jpg",
        count: 1
    },
    {
        id: "FN-UX-EYEW000064",
        name: "BLACK METAL FRAME SUNGLASSES",
        url: "",
        price: 380,
        color: "Black",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/glasses/BLACK-METAL-FRAME/black-metal-frame-product-image.jpg",
        hoverUrl: "/assets/products/glasses/BLACK-METAL-FRAME/black-glasses-hover.png",
        infoImageUrl: "/assets/products/glasses/BLACK-METAL-FRAME/black-glasses-info-image.jpg",
        infoImageUrl2: "/assets/products/glasses/BLACK-METAL-FRAME/black-glasses-closeup.jpg",
        infoImageUrl3: "/assets/products/glasses/BLACK-METAL-FRAME/black-glasses-hover.png",
        infoImageUrl4: "/assets/products/glasses/BLACK-METAL-FRAME/black-glasses-detail.jpg",
        infoImageUrl5: "/assets/products/glasses/BLACK-METAL-FRAME/black-glasses-detail2.jpg",
        infoImageUrl6: "/assets/products/glasses/BLACK-METAL-FRAME/black-glasses-detail4.jpg",
        count: 1
    },
    {
        id: "FN-UX-EYEW000065",
        name: "WHITE METAL FRAME SUNGLASSES",
        url: "",
        price: 380,
        color: "White",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/glasses/WHITE-METAL-FRAME/white-metal-frame-product-imahe.jpg",
        hoverUrl: "/assets/products/glasses/WHITE-METAL-FRAME/white-glasses-model.jpg",
        infoImageUrl: "/assets/products/glasses/WHITE-METAL-FRAME/white-glasses-info-image.jpg",
        infoImageUrl2: "/assets/products/glasses/WHITE-METAL-FRAME/white-glasses-model.jpg",
        infoImageUrl3: "/assets/products/glasses/WHITE-METAL-FRAME/white-glasses-front.jpg",
        infoImageUrl4: "/assets/products/glasses/WHITE-METAL-FRAME/white-glasses-back.jpg",
        infoImageUrl5: "/assets/products/glasses/WHITE-METAL-FRAME/white-glasses-detail1.jpg",
        infoImageUrl6: "/assets/products/glasses/WHITE-METAL-FRAME/white-glasses-detail2.jpg",
        count: 1
    },
    {
        id: "FN-UX-JEWE000430",
        name: "TRIO MIX RING",
        url: "",
        price: 350,
        color: "Antique Silver/Antique Gold",
        description: "Acne Studios antique silver/antique gold ring features three mixed rings in antique silver and gold-toned.",
        imageUrl: "/assets/products/accessories/TRIO-MIX-RING/trio-mix-ring-info-image.jpg",
        hoverUrl: "/assets/products/accessories/TRIO-MIX-RING/trio-mix-ring-profile2.jpg",
        infoImageUrl: "/assets/products/accessories/TRIO-MIX-RING/trio-mix-ring-info-image.jpg",
        infoImageUrl2: "/assets/products/accessories/TRIO-MIX-RING/trio-mix-ring-profile.jpg",
        infoImageUrl3: "/assets/products/accessories/TRIO-MIX-RING/trio-mix-ring-profile2.jpg",
        infoImageUrl4: "/assets/products/accessories/TRIO-MIX-RING/trio-mix-ring-detail.jpg",
        infoImageUrl5: "",
        infoImageUrl6: "",
        count: 1
    },
    {
        id: "FN-UX-JEWE000422",
        name: "MULTI HOOP EARRINGS",
        url: "",
        price: 380,
        color: "Black",
        description: "Acne Studios black relaxed fit jeans feature a 5-pocket denim construction with a high waist, wide leg and long length. The 2022 jeans are crafted from rigid denim made of cotton.",
        imageUrl: "/assets/products/accessories/MULTI-HOOP-EARRINGS/multi-hoop-earrings-product-image.jpg",
        hoverUrl: "/assets/products/accessories/MULTI-HOOP-EARRINGS/multi-hoop-model1.jpg",
        infoImageUrl: "/assets/products/accessories/MULTI-HOOP-EARRINGS/multi-hoop-model-info-image.jpg",
        infoImageUrl2: "assets/products/accessories/MULTI-HOOP-EARRINGS/multi-hoop-model1.jpg",
        infoImageUrl3: "assets/products/accessories/MULTI-HOOP-EARRINGS/multi-hoop-model2.jpg",
        infoImageUrl4: "/assets/products/accessories/MULTI-HOOP-EARRINGS/multi-hoop-detail.jpg",
        infoImageUrl5: "",
        infoImageUrl6: "",
        count: 1
    },
    {
        id: "Beige-Multi-Pocket-Bag",
        name: "MULTIPOCKET MINI BAG",
        url: "",
        price: "1,300",
        color: "Beige/Green",
        description: "Acne Studios beige green multipocket bag is crafted from tanned leather with a chromed finish, complete with pocket compartments and brass finishing.",
        imageUrl: "/assets/products/bags/MULTIPOCKET-MINI-BAG/MPB-info-image.jpg",
        hoverUrl: "",
        infoImageUrl: "/assets/products/bags/MULTIPOCKET-MINI-BAG/MPB-info-image.jpg",
        infoImageUrl2: "/assets/products/bags/MULTIPOCKET-MINI-BAG/MPB-full-body.jpg",
        infoImageUrl3: "/assets/products/bags/MULTIPOCKET-MINI-BAG/MPB-detail1.jpg",
        infoImageUrl4: "/assets/products/bags/MULTIPOCKET-MINI-BAG/MPB-detail2.jpg",
        infoImageUrl5: "/assets/products/bags/MULTIPOCKET-MINI-BAG/MPB-detail3.jpg",
        infoImageUrl6: "/assets/products/bags/MULTIPOCKET-MINI-BAG/MPB-detail4.jpg",
        count: 1
    },
    {
        id: "MultiPocket-Bag",
        name: "MULTIPOCKET BAG",
        url: "",
        price: "1,550",
        color: "Black/Beige",
        description: "Acne Studios black/beige multipocket bag is crafted from tanned leather with pocket compartments.",
        imageUrl: "/assets/products/bags/MULTIPOCKET-BAG/black-multipocket-info-image.jpg",
        hoverUrl: "",
        infoImageUrl: "/assets/products/bags/MULTIPOCKET-BAG/black-multipocket-info-image.jpg",
        infoImageUrl2: "/assets/products/bags/MULTIPOCKET-BAG/black-multipocket-black.jpg",
        infoImageUrl3: "/assets/products/bags/MULTIPOCKET-BAG/black-multipocket-profile.jpg",
        infoImageUrl4: "/assets/products/bags/MULTIPOCKET-BAG/black-multipocket-detail.jpg",
        infoImageUrl5: "/assets/products/bags/MULTIPOCKET-BAG/black-multipocket-detail2.jpg",
        infoImageUrl6: "/assets/products/bags/MULTIPOCKET-BAG/black-multipocket-detail3.jpg",
        count: 1
    },
    
    
]